title: Charles Barnes
email: charles@charlesabarnes.com
description: >- 
  Charles Barnes - Developer in St. Louis, Mo | charles@charlesabarnes.com
url: "https://chkb.net"
baseurl: ""
github_username: charlesabarnes
lang: en_US
author: Charles Barnes
logo: /assets/images/logo.png
social:
  name: Charles Barnes
  links:
    - https://github.com/charlesabarnes
    - https://www.linkedin.com/in/charlesanthonybarnes

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  photography:
    output: true
    permalink: /photography/:path/
  movie_reviews:
    output: true
    permalink: /movie-reviews/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "photography"
    values:
      layout: "photo_album"
  - scope:
      path: ""
      type: "movie_reviews"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/